import type { DayPlan, GrocItem, Plan } from '@/domain/schema';
import { grocId } from '@/domain/groc-id';

/**
 * The curated Finnish–Mediterranean starter week.
 *
 * Two jobs: the instant option for someone who does not want to wait for
 * generation, and the fallback when generation fails. Because it ships in the
 * bundle it always works — offline, key-less, provider-outage-proof.
 *
 * Health guardrail 3: this week is NOT adjusted for allergies. Every place it
 * is offered must say so (see strings.planGate.starter).
 *
 * Monday first, matching `weekdayIdx`.
 */
export const STARTER_DAYS: readonly [
  DayPlan,
  DayPlan,
  DayPlan,
  DayPlan,
  DayPlan,
  DayPlan,
  DayPlan,
] = [
  {
    b: {
      n: 'Blueberry oatmeal',
      fi: 'Kaurapuuro mustikoilla',
      k: 350,
      p: 12,
      c: 52,
      f: 11,
      ing: [
        '80 g rolled oats',
        '2 dl milk or oat drink + 1 dl water',
        '75 g blueberries (frozen is fine)',
        '15 g walnuts, chopped',
        'pinch of cinnamon & salt',
      ],
      st: [
        'Bring oats and liquid to a gentle simmer, stirring.',
        'Cook 5-7 min until creamy; season with salt and cinnamon.',
        'Top with blueberries and walnuts.',
      ],
      yt: 'creamy oatmeal porridge blueberries',
    },
    l: {
      n: 'Light salmon soup',
      fi: 'Lohikeitto',
      k: 480,
      p: 32,
      c: 42,
      f: 19,
      ing: [
        '120 g salmon fillet, cubed',
        '200 g potatoes, diced',
        '1 carrot, sliced',
        '½ leek, sliced',
        '0.5 dl oat cooking cream',
        'fish stock cube + 5 dl water',
        'plenty of fresh dill',
        '1 slice rye bread on the side',
      ],
      st: [
        'Simmer potatoes, carrot and leek in the stock ~10 min.',
        "Add salmon and cook gently 5 min; don't let it boil hard.",
        'Stir in oat cream and dill; serve with rye bread.',
      ],
      yt: 'lohikeitto finnish salmon soup recipe',
    },
    s: { n: 'Apple + almonds', k: 180, p: 4, c: 22, f: 9, ing: ['1 apple', '15 g almonds'] },
    d: {
      n: 'Chicken & root vegetable tray bake',
      k: 520,
      p: 38,
      c: 45,
      f: 18,
      ing: [
        '150 g chicken breast',
        '200 g potatoes, in wedges',
        '2 carrots, in chunks',
        '1 red onion, in wedges',
        '1 tbsp rapeseed oil',
        'dried herbs, salt, pepper',
      ],
      st: [
        'Heat oven to 200 °C; toss everything with oil and seasoning.',
        'Spread on a tray and roast 30-35 min until the chicken is cooked through.',
        'Rest 5 min, then plate.',
      ],
      yt: 'chicken vegetable tray bake healthy',
    },
    e: {
      n: 'Skyr with berries',
      k: 120,
      p: 15,
      c: 12,
      f: 1,
      ing: ['150 g skyr or quark', '50 g berries'],
    },
  },
  {
    b: {
      n: 'Rye bread with egg & vegetables',
      fi: 'Ruisleipä + kananmuna',
      k: 340,
      p: 17,
      c: 38,
      f: 12,
      ing: [
        '2 slices rye bread',
        '1 boiled egg',
        'thin layer of plant-based spread',
        'tomato & cucumber slices',
      ],
      st: [
        'Boil the egg 8-9 min; cool and slice.',
        'Spread the bread thinly; layer egg and vegetables.',
        'Finish with black pepper.',
      ],
      yt: 'rye bread open sandwich egg',
    },
    l: {
      n: 'Red lentil & tomato soup',
      k: 430,
      p: 20,
      c: 62,
      f: 9,
      ing: [
        '80 g red lentils, rinsed',
        '200 g crushed tomatoes',
        '1 onion + 1 garlic clove, chopped',
        '1 carrot, grated',
        '1 tsp ground cumin',
        'vegetable stock cube + 5 dl water',
        '1 wholegrain roll',
      ],
      st: [
        'Soften onion, garlic and carrot in a splash of oil.',
        'Add lentils, tomatoes, stock and cumin; simmer 15 min.',
        'Blend roughly if you like; serve with the roll.',
      ],
      yt: 'red lentil tomato soup easy',
    },
    s: { n: 'Skyr + berries', k: 150, p: 16, c: 16, f: 1, ing: ['150 g skyr', '75 g berries'] },
    d: {
      n: 'Oven-baked salmon & vegetables',
      fi: 'Uunilohi',
      k: 560,
      p: 36,
      c: 38,
      f: 26,
      ing: [
        '140 g salmon fillet',
        '150 g potatoes',
        '150 g broccoli',
        '½ lemon',
        '1 tbsp rapeseed oil',
        'salt, pepper, dill',
      ],
      st: [
        'Heat oven to 200 °C; give the potatoes a 15 min head start.',
        'Add salmon and broccoli; drizzle with oil and lemon.',
        'Roast 15 min more until the salmon flakes; finish with dill.',
      ],
      yt: 'uunilohi oven baked salmon',
    },
    e: {
      n: 'Rye crisps + cottage cheese',
      k: 130,
      p: 12,
      c: 14,
      f: 3,
      ing: ['2 rye crispbreads', '50 g cottage cheese'],
    },
  },
  {
    b: {
      n: 'Apple-cinnamon overnight oats',
      k: 360,
      p: 14,
      c: 54,
      f: 10,
      ing: [
        '70 g rolled oats',
        '150 g plain yogurt',
        '0.5 dl milk',
        '½ apple, grated (rest for topping)',
        '1 tsp ground flaxseed',
        'cinnamon',
      ],
      st: [
        'Mix everything the evening before.',
        'Refrigerate overnight.',
        'Top with the rest of the apple in the morning.',
      ],
      yt: 'overnight oats apple cinnamon',
    },
    l: {
      n: 'Chicken & quinoa bowl',
      k: 500,
      p: 36,
      c: 48,
      f: 16,
      ing: [
        '130 g chicken breast',
        '70 g quinoa (dry)',
        'tomato & cucumber, diced',
        '50 g plain yogurt + garlic + lemon',
        '1 tsp olive oil',
        'paprika powder',
      ],
      st: [
        'Cook quinoa per the pack; pan-fry the seasoned chicken.',
        'Stir garlic and lemon into the yogurt.',
        'Bowl it up: quinoa, chicken, vegetables, sauce on top.',
      ],
      yt: 'chicken quinoa bowl yogurt sauce',
    },
    s: {
      n: 'Carrot sticks + hummus',
      k: 160,
      p: 5,
      c: 16,
      f: 8,
      ing: ['2 carrots', '50 g hummus'],
    },
    d: {
      n: 'Wholegrain pasta with tuna & olives',
      k: 520,
      p: 32,
      c: 62,
      f: 14,
      ing: [
        '80 g wholegrain pasta (dry)',
        '1 can tuna in water, drained',
        '150 g crushed tomatoes',
        '1 garlic clove',
        '20 g olives, sliced',
        '2 handfuls spinach',
      ],
      st: [
        'Boil the pasta; save a splash of pasta water.',
        'Simmer garlic, tomatoes and olives 5 min; fold in tuna and spinach.',
        'Toss with the pasta, loosening with pasta water.',
      ],
      yt: 'tuna tomato pasta healthy',
    },
    e: { n: 'A piece of fruit', k: 80, p: 1, c: 20, f: 0, ing: ['1 pear or orange'] },
  },
  {
    b: {
      n: 'Skyr & muesli bowl',
      k: 340,
      p: 22,
      c: 44,
      f: 7,
      ing: ['200 g skyr', '40 g unsweetened muesli', '75 g berries'],
      st: ['Layer skyr, muesli and berries. Done.'],
      yt: 'skyr muesli breakfast bowl',
    },
    l: {
      n: 'Pea soup with mustard',
      fi: 'Hernekeitto',
      k: 450,
      p: 24,
      c: 64,
      f: 8,
      ing: [
        '100 g dried green peas, soaked (or a carton of pea soup base)',
        '1 onion, chopped',
        '1 tsp mustard',
        'marjoram, salt',
        '2 slices rye bread',
      ],
      st: [
        'Simmer soaked peas with the onion ~60 min until soft (or heat the carton base).',
        'Season with mustard and marjoram.',
        'Serve with rye bread.',
      ],
      yt: 'hernekeitto finnish pea soup',
    },
    s: { n: 'Pear + walnuts', k: 180, p: 3, c: 24, f: 8, ing: ['1 pear', '15 g walnuts'] },
    d: {
      n: 'Greek chicken salad with pita',
      k: 520,
      p: 38,
      c: 40,
      f: 22,
      ing: [
        '130 g chicken breast',
        '30 g feta, crumbled',
        'cucumber, tomato, red onion',
        '20 g olives',
        '1 tbsp olive oil + lemon',
        '1 wholegrain pita',
      ],
      st: [
        'Grill or pan-fry the chicken; slice it.',
        'Chop vegetables; toss with oil, lemon, olives and feta.',
        'Top with chicken; warm the pita on the side.',
      ],
      yt: 'greek chicken salad recipe',
    },
    e: { n: 'Plain yogurt', k: 100, p: 8, c: 10, f: 3, ing: ['150 g plain yogurt'] },
  },
  {
    b: {
      n: 'Banana-peanut oatmeal',
      k: 380,
      p: 13,
      c: 58,
      f: 11,
      ing: [
        '70 g rolled oats',
        '2 dl milk or oat drink',
        '½ banana, sliced',
        '15 g peanut butter',
        'pinch of salt',
      ],
      st: [
        'Simmer the oats in milk 5-7 min.',
        'Stir in the peanut butter off the heat.',
        'Top with banana.',
      ],
      yt: 'peanut butter banana oatmeal',
    },
    l: {
      n: 'Smoked salmon & spinach wrap',
      k: 480,
      p: 28,
      c: 46,
      f: 20,
      ing: [
        '1 wholegrain tortilla',
        '100 g hot-smoked salmon, flaked',
        'a handful of spinach',
        '50 g skyr + a squeeze of lemon',
        'cucumber sticks on the side',
      ],
      st: [
        'Mix skyr with lemon; spread over the tortilla.',
        'Layer spinach and salmon; roll tightly.',
        'Halve and serve with cucumber.',
      ],
      yt: 'smoked salmon wrap healthy',
    },
    s: {
      n: 'Rye crisps, cottage cheese & tomato',
      k: 150,
      p: 12,
      c: 16,
      f: 4,
      ing: ['2 rye crispbreads', '50 g cottage cheese', '1 tomato'],
    },
    d: {
      n: 'Chickpea & vegetable stew, brown rice',
      k: 540,
      p: 20,
      c: 78,
      f: 14,
      ing: [
        '1 can chickpeas, drained',
        '200 g crushed tomatoes',
        '1 bell pepper + 1 small zucchini',
        '1 onion + 1 garlic clove',
        '1 tsp cumin + 1 tsp paprika powder',
        '70 g brown rice (dry)',
      ],
      st: [
        'Cook the rice per the pack.',
        'Soften onion, garlic and vegetables; add the spices.',
        'Add chickpeas and tomatoes; simmer 12 min; serve over rice.',
      ],
      yt: 'chickpea vegetable stew easy',
    },
    e: { n: 'Skyr + berries', k: 110, p: 12, c: 12, f: 1, ing: ['100 g skyr', '50 g berries'] },
  },
  {
    b: {
      n: 'Spinach & tomato omelette + rye',
      k: 380,
      p: 22,
      c: 28,
      f: 18,
      ing: [
        '2 eggs',
        'a handful of spinach',
        '1 tomato',
        '1 slice rye bread',
        '1 tsp rapeseed oil',
      ],
      st: [
        'Whisk the eggs with a pinch of salt.',
        'Cook gently with spinach and tomato until just set.',
        'Serve with rye bread.',
      ],
      yt: 'spinach tomato omelette',
    },
    l: {
      n: 'Rainbow trout, dill potatoes & pickled cucumber',
      fi: 'Kirjolohi',
      k: 520,
      p: 34,
      c: 48,
      f: 20,
      ing: [
        '140 g rainbow trout fillet',
        '250 g potatoes',
        'fresh dill',
        '½ cucumber, thinly sliced',
        '1 tbsp vinegar + pinch of sugar',
        '1 tsp rapeseed oil',
      ],
      st: [
        'Boil the potatoes; pan-fry or bake the trout ~10 min.',
        'Quick-pickle the cucumber in vinegar while it cooks.',
        'Plate everything with plenty of dill.',
      ],
      yt: 'rainbow trout dill potatoes',
    },
    s: {
      n: 'Berries + yogurt',
      k: 140,
      p: 8,
      c: 18,
      f: 3,
      ing: ['100 g berries', '100 g plain yogurt'],
    },
    d: {
      n: 'Turkey meatballs, root mash & lingonberry',
      k: 560,
      p: 38,
      c: 50,
      f: 22,
      ing: [
        '150 g turkey mince',
        '2 tbsp rolled oats + splash of milk (binder)',
        '250 g potato + carrot, for mash',
        '1 tbsp lingonberry jam',
        'salt, pepper, allspice',
      ],
      st: [
        'Mix mince, oats, milk and spices; roll into balls.',
        'Bake 15 min at 200 °C (or pan-fry).',
        'Boil and mash the potato + carrot; serve with a spoonful of lingonberry.',
      ],
      yt: 'turkey meatballs oven healthy',
    },
    e: {
      n: 'Small handful of nuts',
      k: 100,
      p: 3,
      c: 3,
      f: 9,
      ing: ['15 g almonds & walnuts'],
    },
  },
  {
    b: {
      n: 'Oat pancakes with berries',
      k: 400,
      p: 16,
      c: 56,
      f: 12,
      ing: [
        '60 g rolled oats, blitzed to flour',
        '1 egg',
        '½ banana, mashed',
        '0.5 dl milk',
        '100 g berries',
        '50 g yogurt to top',
      ],
      st: [
        'Blend oats, egg, banana and milk into a batter; rest 5 min.',
        'Fry small pancakes ~2 min per side.',
        'Top with berries and yogurt.',
      ],
      yt: 'healthy oat pancakes recipe',
    },
    l: {
      n: 'Roast chicken with oven vegetables',
      k: 520,
      p: 40,
      c: 44,
      f: 18,
      ing: [
        '150 g chicken breast or thigh fillet',
        '200 g potatoes',
        '2 carrots',
        '1 onion',
        '1 tbsp rapeseed oil',
        'rosemary or thyme',
      ],
      st: [
        'Heat oven to 200 °C; toss everything with oil and herbs.',
        'Roast 30-35 min until golden.',
        'Rest briefly and serve.',
      ],
      yt: 'roast chicken vegetables one pan',
    },
    s: { n: 'Orange + almonds', k: 170, p: 4, c: 22, f: 8, ing: ['1 orange', '15 g almonds'] },
    d: {
      n: 'Mediterranean fish stew with barley',
      k: 500,
      p: 34,
      c: 56,
      f: 12,
      ing: [
        '150 g white fish (e.g. pollock)',
        '200 g crushed tomatoes',
        '1 bell pepper + 1 onion + garlic',
        '60 g pearl barley (dry)',
        'paprika powder, pinch of chili',
        'parsley or dill',
      ],
      st: [
        'Cook the barley per the pack.',
        'Simmer onion, garlic, pepper and tomatoes 8 min.',
        'Add fish chunks; poach 5-6 min; serve over barley.',
      ],
      yt: 'mediterranean fish stew tomato',
    },
    e: { n: 'Skyr', k: 100, p: 11, c: 8, f: 1, ing: ['100 g skyr'] },
  },
];

/** Shopping list for the starter week, one person. */
const STARTER_GROC_SOURCE: readonly Omit<GrocItem, 'id'>[] = [
  { cat: 'Fish & meat', n: 'Salmon fillet', fi: 'lohifilee', q: '≈ 260 g' },
  { cat: 'Fish & meat', n: 'Hot-smoked salmon', fi: 'savulohi', q: '100 g' },
  { cat: 'Fish & meat', n: 'Rainbow trout fillet', fi: 'kirjolohifilee', q: '≈ 140 g' },
  { cat: 'Fish & meat', n: 'White fish (pollock)', fi: 'seiti', q: '≈ 150 g' },
  { cat: 'Fish & meat', n: 'Chicken breast', fi: 'broilerin rintafilee', q: '≈ 560 g' },
  {
    cat: 'Fish & meat',
    n: 'Turkey mince',
    fi: 'kalkkunajauheliha',
    q: 'smallest pack (150 g used)',
  },
  { cat: 'Fish & meat', n: 'Tuna in water', fi: 'tonnikala vedessä', q: '1 can' },
  { cat: 'Dairy & eggs', n: 'Eggs', fi: 'kananmunat', q: '6-pack (4 used)' },
  { cat: 'Dairy & eggs', n: 'Skyr or quark, plain', fi: 'maitorahka', q: '≈ 800 g' },
  { cat: 'Dairy & eggs', n: 'Plain yogurt', fi: 'maustamaton jogurtti', q: '≈ 500 g' },
  { cat: 'Dairy & eggs', n: 'Cottage cheese', fi: 'raejuusto', q: '200 g' },
  { cat: 'Dairy & eggs', n: 'Feta', fi: 'fetajuusto', q: 'small block (30 g used)' },
  { cat: 'Dairy & eggs', n: 'Oat cooking cream', fi: 'kaurakerma', q: '1 small carton' },
  { cat: 'Dairy & eggs', n: 'Milk or oat drink', fi: 'kauramaito', q: '1 L' },
  {
    cat: 'Dairy & eggs',
    n: 'Plant-based spread',
    fi: 'kasvirasvalevite',
    q: '1 tub',
    st: true,
  },
  { cat: 'Fruit & vegetables', n: 'Potatoes', fi: 'peruna', q: '≈ 1.3 kg' },
  { cat: 'Fruit & vegetables', n: 'Carrots', fi: 'porkkana', q: '≈ 800 g' },
  { cat: 'Fruit & vegetables', n: 'Onions', fi: 'sipuli', q: '5' },
  { cat: 'Fruit & vegetables', n: 'Red onions', fi: 'punasipuli', q: '2' },
  { cat: 'Fruit & vegetables', n: 'Garlic', fi: 'valkosipuli', q: '1 bulb' },
  { cat: 'Fruit & vegetables', n: 'Leek', fi: 'purjo', q: '1' },
  { cat: 'Fruit & vegetables', n: 'Tomatoes', fi: 'tomaatti', q: '6' },
  { cat: 'Fruit & vegetables', n: 'Cucumber', fi: 'kurkku', q: '2' },
  { cat: 'Fruit & vegetables', n: 'Spinach', fi: 'pinaatti', q: '150 g bag' },
  { cat: 'Fruit & vegetables', n: 'Broccoli', fi: 'parsakaali', q: '1 head' },
  { cat: 'Fruit & vegetables', n: 'Bell peppers', fi: 'paprika', q: '2' },
  { cat: 'Fruit & vegetables', n: 'Zucchini', fi: 'kesäkurpitsa', q: '1 small' },
  { cat: 'Fruit & vegetables', n: 'Lemons', fi: 'sitruuna', q: '2' },
  { cat: 'Fruit & vegetables', n: 'Apples', fi: 'omena', q: '3' },
  { cat: 'Fruit & vegetables', n: 'Pears', fi: 'päärynä', q: '2' },
  { cat: 'Fruit & vegetables', n: 'Bananas', fi: 'banaani', q: '2' },
  { cat: 'Fruit & vegetables', n: 'Oranges', fi: 'appelsiini', q: '2' },
  { cat: 'Fruit & vegetables', n: 'Frozen berry mix', fi: 'pakastemarjat', q: '600 g' },
  { cat: 'Fruit & vegetables', n: 'Fresh dill', fi: 'tilli', q: '1 bunch' },
  { cat: 'Bread & grains', n: 'Rolled oats', fi: 'kaurahiutaleet', q: '500 g' },
  { cat: 'Bread & grains', n: 'Rye bread', fi: 'ruisleipä', q: '1 loaf' },
  { cat: 'Bread & grains', n: 'Rye crispbread', fi: 'näkkileipä', q: '1 pack' },
  { cat: 'Bread & grains', n: 'Wholegrain rolls', fi: 'täysjyväsämpylä', q: '2' },
  { cat: 'Bread & grains', n: 'Wholegrain tortillas', fi: 'täysjyvätortilla', q: '1 pack' },
  { cat: 'Bread & grains', n: 'Wholegrain pita', fi: 'täysjyväpita', q: '1 pack' },
  { cat: 'Bread & grains', n: 'Wholegrain pasta', fi: 'täysjyväpasta', q: '200 g' },
  { cat: 'Bread & grains', n: 'Quinoa', fi: 'kvinoa', q: '100 g' },
  { cat: 'Bread & grains', n: 'Brown rice', fi: 'tumma riisi', q: '150 g' },
  { cat: 'Bread & grains', n: 'Pearl barley', fi: 'ohrasuurimo', q: '100 g' },
  { cat: 'Bread & grains', n: 'Muesli, unsweetened', fi: 'mysli', q: 'small pack' },
  { cat: 'Pantry & cans', n: 'Crushed tomatoes', fi: 'tomaattimurska', q: '3 × 400 g' },
  { cat: 'Pantry & cans', n: 'Red lentils', fi: 'punaiset linssit', q: '100 g' },
  { cat: 'Pantry & cans', n: 'Dried peas / pea soup base', fi: 'herne', q: '1' },
  { cat: 'Pantry & cans', n: 'Chickpeas', fi: 'kikherneet', q: '1 can' },
  { cat: 'Pantry & cans', n: 'Hummus', fi: 'hummus', q: '100 g' },
  { cat: 'Pantry & cans', n: 'Olives', fi: 'oliivit', q: '1 small jar' },
  { cat: 'Pantry & cans', n: 'Walnuts', fi: 'saksanpähkinä', q: '100 g' },
  { cat: 'Pantry & cans', n: 'Almonds', fi: 'manteli', q: '100 g' },
  { cat: 'Pantry & cans', n: 'Peanut butter', fi: 'maapähkinävoi', q: '1 jar', st: true },
  { cat: 'Pantry & cans', n: 'Rapeseed oil', fi: 'rypsiöljy', q: '1 bottle', st: true },
  { cat: 'Pantry & cans', n: 'Olive oil', fi: 'oliiviöljy', q: '1 bottle', st: true },
  { cat: 'Pantry & cans', n: 'Lingonberry jam', fi: 'puolukkahillo', q: 'small jar' },
  {
    cat: 'Pantry & cans',
    n: 'Ground flaxseed',
    fi: 'pellavansiemenrouhe',
    q: 'small pack',
    st: true,
  },
  {
    cat: 'Pantry & cans',
    n: 'Stock cubes (fish + vegetable)',
    fi: 'liemikuutio',
    q: '1 pack',
    st: true,
  },
  { cat: 'Pantry & cans', n: 'Mustard', fi: 'sinappi', q: '1', st: true },
  { cat: 'Pantry & cans', n: 'Ground cumin', fi: 'roomankumina', q: '1 jar', st: true },
  { cat: 'Pantry & cans', n: 'Paprika powder', fi: 'paprikajauhe', q: '1 jar', st: true },
  { cat: 'Pantry & cans', n: 'Cinnamon', fi: 'kaneli', q: '1 jar', st: true },
  { cat: 'Pantry & cans', n: 'Marjoram', fi: 'meirami', q: '1 jar', st: true },
  { cat: 'Pantry & cans', n: 'Allspice', fi: 'maustepippuri', q: '1 jar', st: true },
  { cat: 'Pantry & cans', n: 'Rosemary or thyme', fi: 'rosmariini', q: '1 jar', st: true },
  { cat: 'Pantry & cans', n: 'Vinegar (for pickling)', fi: 'etikka', q: '1 bottle', st: true },
];

/** Ids are derived from the Finnish name, exactly as generated lists are. */
export const STARTER_GROC: readonly GrocItem[] = STARTER_GROC_SOURCE.map((item) => ({
  id: grocId(item.fi),
  ...item,
}));

/** Build the starter plan as a storable plan document. */
export function starterPlan(createdAt: number): Plan {
  return {
    v: 1,
    created: createdAt,
    starter: true,
    days: [...STARTER_DAYS],
    groc: [...STARTER_GROC],
  };
}
